---------------------------------------TB_MEMBER------------------------------------------
CREATE TABLE TB_MEMBER(
    USER_ID VARCHAR2(30 CHAR) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR2(60 CHAR) NOT NULL,
    EMAIL VARCHAR2(50 CHAR) NOT NULL,
    GRADE CHAR(4) DEFAULT 'ME00',
    TELL VARCHAR2(15 CHAR),
    REG_DATE DATE DEFAULT SYSDATE,
    RENTABLE_DATE DATE DEFAULT TO_DATE(SYSDATE,'YYYY/MM/DD'),
    IS_LEAVE NUMBER DEFAULT 0 NOT NULL
);
---------------------------------------TB_BOARD------------------------------------------
CREATE TABLE TB_BOARD(
    BD_IDX NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30 CHAR) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    TITLE VARCHAR2(50 CHAR) NOT NULL,
    CONTENT VARCHAR2(2000 CHAR) NOT NULL,
    IS_DEL NUMBER DEFAULT 0,
    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(USER_ID) REFERENCES TB_MEMBER(USER_ID)
  --ON DELETE CASCADE
  --ON DELETE SET NULL
);

---------------------------------------TB_FILE------------------------------------------
CREATE TABLE TB_FILE(
    F_IDX NUMBER PRIMARY KEY,
    TYPE_IDX NUMBER NOT NULL,
    TYPE VARCHAR2(30 CHAR) NOT NULL,
    ORIGIN_FILE_NAME VARCHAR2(260 CHAR) NOT NULL,
    RENAME_FILE_NAME VARCHAR2(260 CHAR) NOT NULL,
   SAVE_PATH VARCHAR2(260 CHAR) NOT NULL,
   REGDATE DATE  DEFAULT SYSDATE,
   IS_DEL NUMBER DEFAULT 0
);
---------------------------------------TB_RENT_MASTER------------------------------------------
CREATE TABLE TB_RENT_MASTER (
	RM_IDX 	 NUMBER	PRIMARY KEY,
	USER_ID	 VARCHAR2(30 CHAR)		NOT NULL,
	REG_DATE	DATE	DEFAULT SYSDATE	NULL,
	IS_RETURN	NUMBER	DEFAULT 0	NULL,
	TITLE	VARCHAR2(300 CHAR)		NOT NULL,
	RENT_BOOK_CNT	NUMBER		NOT NULL,
    CONSTRAINT FK__RENTMASTER_MEMBER FOREIGN KEY(USER_ID) REFERENCES TB_MEMBER(USER_ID)
);
---------------------------------------TB_RENT_BOOK------------------------------------------    
CREATE TABLE TB_RENT_BOOK (
	RB_IDX	NUMBER	PRIMARY KEY,
	RM_IDX	NUMBER		NOT NULL,
	B_IDX 	NUMBER		NOT NULL,
	REG_DATE	DATE	 DEFAULT SYSDATE	NULL,
	STATE	VARCHAR2(4 CHAR)	DEFAULT 'RE00'	NULL,
	RETURN_DATE	 DATE	DEFAULT TO_DATE(SYSDATE,'YYYY/MM/DD')+7	NULL,
	EXTENTION_CNT	NUMBER	DEFAULT 0 	NULL,
    CONSTRAINT FK_RENTBOOK_RENTMASTER FOREIGN KEY(RM_IDX) REFERENCES TB_RENT_MASTER(RM_IDX),
    CONSTRAINT FK_RENTBOOK_BOOK FOREIGN KEY(B_IDX) REFERENCES TB_BOOK(B_IDX)
);

---------------------------------------TB_CODE------------------------------------------    
CREATE TABLE TB_CODE (
	CODE	VARCHAR2(4 CHAR)	PRIMARY KEY,
	UPPER_CD  VARCHAR2(4 CHAR)		NULL,
	INFO	VARCHAR2(300 CHAR)		NOT NULL,
	REG_DATE	DATE 	DEFAULT SYSDATE	NULL
);
    
---------------------------------------TB_RENT_HISTORY------------------------------------------        
CREATE TABLE TB_RENT_HISTORY (
	RH_IDX 	 NUMBER	PRIMARY KEY,
	RM_IDX  	NUMBER		NOT NULL,
	RB_IDX	NUMBER		NOT NULL,
	B_IDX	    NUMBER		NULL,
	REG_DATE	DATE		NULL,
	STATE	CHAR(4 CHAR)	NULL,
    CONSTRAINT FK_RENTHISTORY_RENTBOOK FOREIGN KEY(RB_IDX) REFERENCES TB_RENT_BOOK(RB_IDX),
    CONSTRAINT FK_RENTHISTORY_RENTMASTER FOREIGN KEY(RM_IDX) REFERENCES TB_RENT_MASTER(RM_IDX)
);
---------------------------------------TB_BOOK------------------------------------------       
CREATE TABLE TB_BOOK (
	B_IDX 	NUMBER	PRIMARY KEY,
	ISBN	VARCHAR2(100 CHAR)		NULL,
	CATEGORY	CHAR(4 CHAR)		NULL,
	TITLE	VARCHAR2(100 CHAR)		NOT NULL,
	AUTHOR	VARCHAR2(100 CHAR)		NOT NULL,
	INFO	VARCHAR2(500 CHAR)		NULL,
	BOOK_AMT	NUMBER	DEFAULT 1	NULL,
	REG_DATE	DATE	 DEFAULT SYSDATE	NULL,
	RENT_CNT	NUMBER(6)	DEFAULT 0	NULL
);
---------------------------------------TB_BOOK_RESERVES------------------------------------------       
CREATE TABLE TB_BOOK_RESERVES (
	RES_IDX	NUMBER	PRIMARY KEY,
	B_IDX	 NUMBER		NOT NULL,
	REG_DATE	 DATE	DEFAULT SYSDATE	NULL,
	STATE	VARCHAR2(4CHAR)	DEFAULT 'RS00'	NULL,
    CONSTRAINT FK_BOOKRESERVE_BOOK FOREIGN KEY(B_IDX) REFERENCES TB_BOOK(B_IDX)
);

---------------------------------------TB_BOOK_CART------------------------------------------  
CREATE TABLE TB_BOOK_CART (
	BC_IDX	NUMBER	PRIMARY KEY,
	B_IDX	 NUMBER		NOT NULL,
	USER_ID	VARCHAR2(30char)		NULL,
	SESSION_ID	VARCHAR2(100 CHAR)		NULL,
	REG_DATE DATE	DEFAULT SYSDATE	NULL,
    CONSTRAINT FK_BOOKCART_BOOK FOREIGN KEY(B_IDX) REFERENCES TB_BOOK(B_IDX)
);

------------------------------------INSERT 테스트-------------------------------

--테스트 데이터 추가
INSERT INTO TB_MEMBER(USER_ID, PASSWORD, EMAIL, IS_LEAVE)
VALUES ('AAA','1234','AAA@AAA.COM',0);
INSERT INTO TB_BOARD(BD_IDX, USER_ID, REG_DATE, TITLE, CONTENT)
VALUES(1234,'AAA','20/11/25','테스트','테스트 중입니다.');

SELECT * FROM TB_MEMBER;
SELECT * FROM TB_BOARD;

-- 부모 테이블의 ROW 삭제
DELETE FROM TB_MEMBER WHERE USER_ID = 'AAA';
ALTER TABLE TB_BOARD MODIFY(USER_ID VARCHAR2(30 CHAR) NULL);

DROP TABLE TB_BOARD;
DROP TABLE TB_MEMBER;





    