-- 안풀어도 되는 문제 3, 9, 10 번문제

--1번
SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열  FROM  TB_DEPARTMENT;

--2번
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || ' 명입니다.'  FROM TB_DEPARTMENT;

--3번
--SELECT STUDENT_NAME FROM TB_STUDENT
--WHERE ABSENCE_YN = 'Y' 
--AND DEPARTMENT_NO =
--SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '국어국문학과'";


--4번
SELECT STUDENT_NAME FROM TB_STUDENT 
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119');

--5번
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT
WHERE  CAPACITY BETWEEN 20 AND 30;

--6번
SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NULL;

--7번
SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO IS NULL;

--8번
SELECT CLASS_NO FROM TB_CLASS WHERE preattending_class_no IS NOT NULL;

--9번
SELECT DISTINCT CATEGORY FROM tb_department;

--10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE FROM TB_STUDENT
WHERE  STUDENT_ADDRESS LIKE '%전주%'
AND (ENTRANCE_DATE BETWEEN '02/01/01' AND '02/12/31')
AND  ABSENCE_YN = 'N';


