--SET OPERATION
--집합 연산
--합집합 : UNION (OR) 
--교집합 : INTERSECT (AND)
--차집합 : MINUS 
--UNION ALL : 쿼리 결과를 하나로 합치는 연산자, 중복을 제거하지 않는다.

--UNION : 두 쿼리 결과를 하나로 합치는 연산자
--             중복을 제거한다.
SELECT EMP_ID, EMP_NAME,  DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION 
SELECT EMP_ID, EMP_NAME,  DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;
-- 존나 길다 그냥 조건절에 OR해주면 된다
SELECT EMP_ID, EMP_NAME,  DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5' OR SALARY > 3000000;

--INTERSECT : 두 쿼리의 결과 중 공통 부분만 추출(교집합)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY>3000000;
--마찬가지로 그냥 조건절에 AND해주는거 쓰자
SELECT EMP_ID, EMP_NAME,  DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5' AND SALARY > 3000000;

--MINUS : 차집합 (위의 결과 - 아래 결과)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY>3000000;
--마찬가지로 조건절에 AND NOT 해주면 된다
SELECT EMP_ID, EMP_NAME,  DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'  AND NOT SALARY > 3000000;

--UNION ALL : 조건절로 만들 수없음 알아둘 것
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY>3000000;




