--------------1번--------------
SELECT EMP_NAME, JOB_CODE, SALARY, 
DECODE(JOB_CODE,'J7',SALARY*1.08,'J6',SALARY*1.07,'J5',SALARY*1.05,SALARY*1.03) AS 인상후급여
FROM EMPLOYEE;

--------------2번--------------
SELECT DEPT_CODE, SUM(SALARY) FROM EMPLOYEE
GROUP BY DEPT_CODE HAVING SUM(SALARY) > 9000000;

--------------4번--------------
SELECT EMP_NAME AS 사원명, EMP_NO AS 주민번호, 
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6))) AS 나이,
HIRE_DATE AS 입사일,
EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) AS 근무년수
FROM EMPLOYEE;



----------문제해결1번-------------
SELECT  EMP_NAME, JOB_CODE, COUNT(*) AS 사원수
FROM EMPLOYEE
WHERE BONUS IS NOT NULL
GROUP BY EMP_NAME, JOB_CODE
ORDER BY JOB_CODE ;




------------문제해결 2번------------------
SELECT DEPT_CODE
, SUM(SALARY) 합계
, FLOOR(AVG(SALARY)) 평균
, COUNT(*) 인원수
FROM EMPLOYEE
GROUP BY DEPT_CODE HAVING FLOOR(AVG(SALARY)) > 2800000
ORDER BY DEPT_CODE ASC;

SELECT DEPT_CODE
, SUM(SALARY) 합계
, FLOOR(AVG(SALARY)) 평균
, COUNT(*) 인원수
FROM EMPLOYEE
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE ASC;

--해당 쿼리를 사용해야 하는 이유